import type { Metadata } from "next";
import AuthProvider from "@/context/AuthProvider";
import "./globals.css";

export const metadata: Metadata = {
  title: "v.aibe",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="icon" href="/v.aibe.png" />
      <body className="antialiased font-railway">
        {" "}
        <AuthProvider>{children} </AuthProvider>
      </body>
    </html>
  );
}
